export default {
  PICKUP_ORDERS_FETCH_END: "PICKUP_ORDERS_FETCH_END",
  PICKUP_ORDERS_FETCH_START: "PICKUP_ORDERS_FETCH_START",
  PICKUP_ORDERS_GROUP_END: "PICKUP_ORDERS_GROUP_END",
  PICKUP_ORDERS_GROUP_START: "PICKUP_ORDERS_GROUP_START",
  PICKUP_ORDERS_SET_FILTER: "PICKUP_ORDERS_SET_FILTER",
  PICKUP_ORDERS_SET_LIST: "PICKUP_ORDERS_SET_LIST",
  PICKUP_ORDERS_SET_SELECTED: "PICKUP_ORDERS_SET_SELECTED",
  PICKUP_ORDERS_SET_STATE: "PICKUP_ORDERS_SET_STATE",

  RECEIVED_ORDERS_FETCH_END: "PICKUP_ORDERS_FETCH_END",
  RECEIVED_ORDERS_FETCH_START: "PICKUP_ORDERS_FETCH_START",
  RECEIVED_ORDERS_GROUP_END: "PICKUP_ORDERS_GROUP_END",
  RECEIVED_ORDERS_GROUP_START: "PICKUP_ORDERS_GROUP_START",
  RECEIVED_ORDERS_SET_FILTER: "PICKUP_ORDERS_SET_FILTER",
  RECEIVED_ORDERS_SET_LIST: "PICKUP_ORDERS_SET_LIST",
  RECEIVED_ORDERS_SET_SELECTED: "PICKUP_ORDERS_SET_SELECTED",
  RECEIVED_ORDERS_SET_STATE: "PICKUP_ORDERS_SET_STATE",
};
