export default {
  DETAILS_FETCH_END: "DETAILS_FETCH_END",
  DETAILS_FETCH_START: "DETAILS_FETCH_START",
  DETAILS_SET: "DETAILS_SET",

  EDIT_ORDER_START: "EDIT_ORDER_START",
  EDIT_ORDER_END: "EDIT_ORDER_END",

  PICKUP_ORDERS_FETCH_END: "PICKUP_ORDERS_FETCH_END",
  PICKUP_ORDERS_FETCH_START: "PICKUP_ORDERS_FETCH_START",
  PICKUP_ORDERS_GROUP_END: "PICKUP_ORDERS_GROUP_END",
  PICKUP_ORDERS_GROUP_START: "PICKUP_ORDERS_GROUP_START",
  PICKUP_ORDERS_SET_FILTER: "PICKUP_ORDERS_SET_FILTER",
  PICKUP_ORDERS_SET_LIST: "PICKUP_ORDERS_SET_LIST",
  PICKUP_ORDERS_SET_SELECTED: "PICKUP_ORDERS_SET_SELECTED",
  PICKUP_ORDERS_SET_STATE: "PICKUP_ORDERS_SET_STATE",

  RECEIVED_ORDERS_FETCH_END: "PICKUP_ORDERS_FETCH_END",
  RECEIVED_ORDERS_FETCH_START: "PICKUP_ORDERS_FETCH_START",
  RECEIVED_ORDERS_GROUP_END: "PICKUP_ORDERS_GROUP_END",
  RECEIVED_ORDERS_GROUP_START: "PICKUP_ORDERS_GROUP_START",
  RECEIVED_ORDERS_SET_FILTER: "PICKUP_ORDERS_SET_FILTER",
  RECEIVED_ORDERS_SET_LIST: "PICKUP_ORDERS_SET_LIST",
  RECEIVED_ORDERS_SET_SELECTED: "PICKUP_ORDERS_SET_SELECTED",
  RECEIVED_ORDERS_SET_STATE: "PICKUP_ORDERS_SET_STATE",

  UPDATE_ORDERS_START: "UPDATE_ORDERS_START",
  UPDATE_ORDERS_END: "UPDATE_ORDERS_END",
  SUCCESS_EDITING: "SUCCESS_EDITING",
  REVERT_SUCCESS_EDITING: "REVERT_SUCCESS_EDITING",
};
