export const DRIVERS_FETCH_START = 'DRIVERS_FETCH_START';
export const DRIVERS_FETCH_SUCCESS = 'DRIVERS_FETCH_SUCCESS';
export const DRIVERS_FETCH_FAILED = 'DRIVERS_FETCH_FAILED';

export const DRIVERS_PICK_START = 'DRIVERS_PICK_START';
export const DRIVERS_PICK_SUCCESS = 'DRIVERS_PICK_SUCCESS';
export const DRIVERS_PICK_FAILED = 'DRIVERS_PICK_FAILED';

export const DRIVER_DEASSIGN_START = 'DRIVER_DEASSIGN_START';
export const DRIVER_DEASSIGN_SUCCESS = 'DRIVER_DEASSIGN_SUCCESS';
export const DRIVER_DEASSIGN_FAILED = 'DRIVER_DEASSIGN_FAILED';
