export const TRIP_FETCHDETAIL_START = 'TRIP_FETCHDETAIL_START';
export const TRIP_FETCHDETAIL_SUCCESS = 'TRIP_FETCHDETAIL_SUCCESS';
export const TRIP_FETCHDETAIL_FAILED = 'TRIP_FETCHDETAIL_FAILED';

export const TRIPS_FETCH_START = 'TRIPS_FETCH_START';
export const TRIPS_FETCH_SUCCESS = 'TRIPS_FETCH_SUCCESS';
export const TRIPS_FETCH_FAILED = 'TRIPS_FETCH_FAILED';

export const TRIPS_RESET = 'TRIPS_RESET';
export const TRIPS_SET_CURRENTPAGE = 'TRIPS_SET_CURRENTPAGE';
export const TRIPS_SET_FILTER = 'TRIPS_SET_FILTER';
export const TRIPS_SET_LIMIT = 'TRIPS_SET_LIMIT';
export const TRIPS_SET_QUERYTYPE = 'TRIPS_SET_QUERYTYPE';
