export default {
  TRIP_DETAILS_FETCH_END: "TRIP_DETAILS_FETCH_END",
  TRIP_DETAILS_FETCH_START: "TRIP_DETAILS_FETCH_START",
  TRIP_DETAILS_SET: "TRIP_DETAILS_SET",

  OUTBOUND_TRIPS_FETCH_END: "OUTBOUND_TRIPS_FETCH_END",
  OUTBOUND_TRIPS_FETCH_START: "OUTBOUND_TRIPS_FETCH_START",
  OUTBOUND_TRIPS_SET_FILTER: "OUTBOUND_TRIPS_SET_FILTER",
  OUTBOUND_TRIPS_SET_LIST: "OUTBOUND_TRIPS_SET_LIST",
  OUTBOUND_TRIPS_SET_STATE: "OUTBOUND_TRIPS_SET_STATE",
}
