export default {
  HUB_EDIT_END: "HUB_EDIT_END",
  HUB_EDIT_START: "HUB_EDIT_START",

  HUB_FETCH_END: "HUB_FETCH_END",
  HUB_FETCH_START: "HUB_FETCH_START",
  HUB_SET_LIST: "HUB_SET_LIST",

  HUB_PICK: "HUB_PICK",

  HUB_UPDATE_END: "HUB_UPDATE_END",
  HUB_UPDATE_START: "HUB_UPDATE_START",
}
