export const CONTAINER_ACTIVE_TOGGLE_START = 'CONTAINER_ACTIVE_TOGGLE_START';
export const CONTAINER_ACTIVE_TOGGLE_SUCCESS = 'CONTAINER_ACTIVE_TOGGLE_SUCCESS';
export const CONTAINER_ACTIVE_TOGGLE_FAILED = 'CONTAINER_ACTIVE_TOGGLE_FAILED';

export const CONTAINER_CREATE_START = 'CONTAINER_CREATE_START';
export const CONTAINER_CREATE_SUCCESS = 'CONTAINER_CREATE_SUCCESS';
export const CONTAINER_CREATE_FAILED = 'CONTAINER_CREATE_FAILED';

export const CONTAINER_DETAILS_FETCH_START = 'CONTAINER_DETAILS_FETCH_START';
export const CONTAINER_DETAILS_FETCH_SUCCESS = 'CONTAINER_DETAILS_FETCH_SUCCESS';
export const CONTAINER_DETAILS_FETCH_FAILED = 'CONTAINER_DETAILS_FETCH_FAILED';

export const CONTAINER_DISTRICT_PICK = 'CONTAINER_DISTRICT_PICK';
export const CONTAINER_DISTRICT_RESET = 'CONTAINER_DISTRICT_RESET';

export const CONTAINER_FILL_START = 'CONTAINER_FILL_START';
export const CONTAINER_FILL_SUCCESS = 'CONTAINER_FILL_SUCCESS';
export const CONTAINER_FILL_FAILED = 'CONTAINER_FILL_FAILED';

export const CONTAINERS_FETCH_START = 'CONTAINERS_FETCH_START';
export const CONTAINERS_FETCH_SUCCESS = 'CONTAINERS_FETCH_SUCCESS';
export const CONTAINERS_FETCH_FAILED = 'CONTAINERS_FETCH_FAILED';

export const ORDER_PREPARE_FETCH_START = 'ORDER_PREPARE_FETCH_START';
export const ORDER_PREPARE_FETCH_SUCCESS = 'ORDER_PREPARE_FETCH_SUCCESS';
export const ORDER_PREPARE_FETCH_FAILED = 'ORDER_PREPARE_FETCH_FAILED';

export const ORDER_PREPARE_TOGGLE = 'ORDER_PREPARE_TOGGLE';

export const ORDER_REMOVE_START = 'ORDER_REMOVE_START';
export const ORDER_REMOVE_SUCCESS = 'ORDER_REMOVE_SUCCESS';
export const ORDER_REMOVE_FAILED = 'ORDER_REMOVE_FAILED';

export const containerDistrictPick = (containerID, districtID) => ({type: CONTAINER_DISTRICT_PICK, containerID: containerID, districtID: districtID});

export const containerDistrictReset = (containerID) => ({type: CONTAINER_DISTRICT_RESET, containerID: containerID});
