export const CHECK_AUTH = 'CHECK_AUTH_START';
export const AUTH_VALID = 'CHECK_AUTH_SUCCESS';
export const AUTH_INVALID = 'CHECK_AUTH_FAILED';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGIN_GOOGLE_START = 'LOGIN_GOOLE_START';
export const LOGIN_GOOGLE_SUCCESS = 'LOGIN_GOOGLE_SUCCESS';
export const LOGIN_GOOGLE_FAILED = 'LOGIN_GOOGLE_FAILED';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';
